### ISSUE TITLE
gramatron  Segmentation fault on Ubuntu20.04

### ISSUE THREAD

**Issue by phoenixltx** [HexHive/Gramatron#3]
I installed Gramatron from scratch,and run the ruby test,it has this error:
root@test:/home/Gramatron/src/gramfuzz-mutator# ./run_campaign.sh /home/Gramatron/grammars/ruby/source_automata.json test_output "/tmp/mruby/bin/mruby @@"
./run_campaign.sh: line 34: 1026037 Segmentation fault      $FUZZ_MAIN -m none -a $AUTOMATON -i $INPUT_DIR -o $OUTPUT_DIR -- $RUNCMD
then I use this command to see what happens:
../afl-gf/afl-fuzz -m none -a /home/Gramatron/grammars/ruby/source_automata.json -i /tmp/inputs -o ruby_output -- /tmp/mruby/bin/mruby @@
...
[-]  SYSTEM ERROR : Unable to open '/tmp/inputs/001.aut.aut'
    Stop location : link_or_copy(), src/afl-fuzz-init.c:760
       OS message : No such file or directory
then I list the inputs folder:
root@test:/tmp/inputs# ls
001.aut  004  007  010  013  016  019  022  025  028  031  034  037  040  043  046  049  052  055  058  061  064  067  070  073  076  079  082  085  088  091  094  097  100
002      005  008  011  014  017  020  023  026  029  032  035  038  041  044  047  050  053  056  059  062  065  068  071  074  077  080  083  086  089  092  095  098
003      006  009  012  015  018  021  024  027  030  033  036  039  042  045  048  051  054  057  060  063  066  069  072  075  078  081  084  087  090  093  096  099

which is not the same as the inputs folder in your docker image:
root@fda4e3695b91:/tmp/inputs# ls
001      005.aut  010      014.aut  019      023.aut  028      032.aut  037      041.aut  046      050.aut  055      059.aut  064      068.aut  073      077.aut  082      086.aut  091      095.aut  100
001.aut  006      010.aut  015      019.aut  024      028.aut  033      037.aut  042      046.aut  051      055.aut  060      064.aut  069      073.aut  078      082.aut  087      091.aut  096      100.aut
002      006.aut  011      015.aut  020      024.aut  029      033.aut  038      042.aut  047      051.aut  056      060.aut  065      069.aut  074      078.aut  083      087.aut  092      096.aut
002.aut  007      011.aut  016      020.aut  025      029.aut  034      038.aut  043      047.aut  052      056.aut  061      065.aut  070      074.aut  079      083.aut  088      092.aut  097
003      007.aut  012      016.aut  021      025.aut  030      034.aut  039      043.aut  048      052.aut  057      061.aut  066      070.aut  075      079.aut  084      088.aut  093      097.aut
003.aut  008      012.aut  017      021.aut  026      030.aut  035      039.aut  044      048.aut  053      057.aut  062      066.aut  071      075.aut  080      084.aut  089      093.aut  098
004      008.aut  013      017.aut  022      026.aut  031      035.aut  040      044.aut  049      053.aut  058      062.aut  067      071.aut  076      080.aut  085      089.aut  094      098.aut
004.aut  009      013.aut  018      022.aut  027      031.aut  036      040.aut  045      049.aut  054      058.aut  063      067.aut  072      076.aut  081      085.aut  090      094.aut  099
005      009.aut  014      018.aut  023      027.aut  032      036.aut  041      045.aut  050      054.aut  059      063.aut  068      072.aut  077      081.aut  086      090.aut  095      099.aut

I just pull the code down,build and run,I don't know why this happens?

**Comment by prashast** [comment]
Hi, sorry for the late response. The reason why this was happening because apparently the globals that were keeping track of the initial and final states read from the automaton description file were being overwritten after the custom mutator library was loaded in. This was a behavior I did not see when testing on Xenial (16.04) but did observe it when running on focal (20.04). To address this issue, I've pushed a minor hack. Please re-open this issue if the problem still persists. For your convenience, I've pushed a separate docker image with Gramatron setup on focal as well. The instructions to get the focal image are listed [here](https://github.com/HexHive/Gramatron#run-a-sample-fuzz-campaign).
